### ISSUE TITLE
"connection failed" trying to use account not specified in config

### ISSUE THREAD

**Issue by gutleib** [shayonj/pg_easy_replicate#16]
During bootstrap phase, pg_easy_replicate fails with 
```
Unable to bootstrap: PG::ConnectionBad: connection to server at "10.7.0.10", port 25432 failed: SSL error: certificate verify failed
connection to server at "10.7.0.10", port 25432 failed: FATAL:  password authentication failed for user "pger_su"
```
message.  That is strange, because `postgres://postgres:secret@10.7.0.10:25432/database` credentials are used.

How can this error be fixed?

**Comment by gutleib** [comment]
I don't know ruby, but I searched source for 'pger_su', and found multiple mentions.
The database I am replicating has such user and it seems to be used. 
Can this user in pg_easy_replicate be uid-generated? 
It is unfortunate that I cannot use some usernames due to coincedental choice.

**Comment by shayonj** [comment]
Hi! Thats a special user the lib creates so that during switchover, when terminating connections, we don't sever the connection between the `publication` and `subscription`. Can you share the output of `config_check`. I wonder if some ssl setting is required here

https://github.com/shayonj/pg_easy_replicate#config-check

**Comment by shayonj** [comment]
> I don't know ruby, but I searched source for 'pger_su', and found multiple mentions.
The database I am replicating has such user and it seems to be used.

Oh interesting. I assumed it would be unique enoug, i guess some alpha-numeric, yet a deterministic key, would be nice. 

I will issue a fix for this soon.

**Comment by shayonj** [comment]
I have released `0.1.2`, if you'd like to try it out. Please note that the gem also created `pger_su` before. Its possible it collided with a user you already had, but the error message, seemed to indicate otherwise. You can try out the new version `0.1.2` and feel free to re-open the issue if you run into the same problem.

**Comment by gutleib** [comment]
Hm. Interestingly, no, error persists, now with pger_su_h1a4fb.

Is there any way to debug process?

I tried `psql` with line identical to one used in `$SOURCE_DB_URL`  and it logs in without a problem...

**Comment by shayonj** [comment]
oh! interesting. The `config_check` command output would be useful. Does that work in your case?

**Comment by shayonj** [comment]
Few more Qs

- are you using docker or the gem is installed on a ruby machine?
- does the PG server require any custom ssl model? 

Thanks!

**Comment by gutleib** [comment]
> are you using docker or the gem is installed on a ruby machine?

I have installed pg_easy_replicate on target-postgres machine, it's a x86_64 VM, so, ruby gem.

> does the PG server require any custom ssl model?

I don't think so. I have observed this ssl error when there was an error in password, but only togeteher with "password authentication failed".

**Comment by shayonj** [comment]
i see! Does the password have any special chars like a single apostrophe (`'`), exclamation mark (`!`) or a tilde (`~`)? 

Its possible there is a parsing bug

**Comment by gutleib** [comment]
> Also, you can set `DEBUG` env var to `true`, it will print any debug logs too.

I tried `-v` and `--debug` to no avail. Guessed wrong!

> oh! interesting. The `config_check` command output would be useful. Does that work in your case?
```
$ pg_easy_replicate config_check
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.288+00:00","v":0,"msg":"(0.002355s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.290+00:00","v":0,"msg":"(0.002567s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.293+00:00","v":0,"msg":"(0.002326s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":20,"time":"2023-06-23T00:26:01.293+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.295+00:00","v":0,"msg":"(0.002261s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.298+00:00","v":0,"msg":"(0.002386s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.302+00:00","v":0,"msg":"(0.004181s) select usesuper from pg_user where usename = 'postgres';","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.305+00:00","v":0,"msg":"(0.002520s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.327+00:00","v":0,"msg":"(0.000177s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.328+00:00","v":0,"msg":"(0.000081s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.328+00:00","v":0,"msg":"(0.000078s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":20,"time":"2023-06-23T00:26:01.328+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.328+00:00","v":0,"msg":"(0.000068s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.328+00:00","v":0,"msg":"(0.000089s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.330+00:00","v":0,"msg":"(0.001414s) select usesuper from pg_user where usename = 'postgres';","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.330+00:00","v":0,"msg":"(0.000085s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.358+00:00","v":0,"msg":"(0.002395s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.361+00:00","v":0,"msg":"(0.002382s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.363+00:00","v":0,"msg":"(0.002426s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":20,"time":"2023-06-23T00:26:01.363+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.366+00:00","v":0,"msg":"(0.002729s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.369+00:00","v":0,"msg":"(0.002602s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.374+00:00","v":0,"msg":"(0.004891s) select name, setting from pg_settings where name in  ('max_wal_senders', 'max_worker_processes', 'wal_level',  'max_replication_slots', 'max_logical_replication_workers');","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.376+00:00","v":0,"msg":"(0.002414s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.398+00:00","v":0,"msg":"(0.000141s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.398+00:00","v":0,"msg":"(0.000087s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.398+00:00","v":0,"msg":"(0.000072s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":20,"time":"2023-06-23T00:26:01.398+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.398+00:00","v":0,"msg":"(0.000069s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.399+00:00","v":0,"msg":"(0.000086s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.401+00:00","v":0,"msg":"(0.001886s) select name, setting from pg_settings where name in  ('max_wal_senders', 'max_worker_processes', 'wal_level',  'max_replication_slots', 'max_logical_replication_workers');","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3868994,"level":30,"time":"2023-06-23T00:26:01.401+00:00","v":0,"msg":"(0.000108s) COMMIT","version":"0.1.2"}
✅ Config is looking good.
```
and
```
$ pg_easy_replicate bootstrap -g dedic-migrate 
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:46.998+00:00","v":0,"msg":"(0.002660s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.001+00:00","v":0,"msg":"(0.003110s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.006+00:00","v":0,"msg":"(0.004850s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":20,"time":"2023-06-23T00:28:47.006+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.011+00:00","v":0,"msg":"(0.004691s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.014+00:00","v":0,"msg":"(0.003282s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.018+00:00","v":0,"msg":"(0.004189s) select usesuper from pg_user where usename = 'postgres';","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.021+00:00","v":0,"msg":"(0.002420s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.044+00:00","v":0,"msg":"(0.000175s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.044+00:00","v":0,"msg":"(0.000089s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.044+00:00","v":0,"msg":"(0.000091s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":20,"time":"2023-06-23T00:28:47.044+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.044+00:00","v":0,"msg":"(0.000077s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.044+00:00","v":0,"msg":"(0.000087s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.046+00:00","v":0,"msg":"(0.001359s) select usesuper from pg_user where usename = 'postgres';","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.046+00:00","v":0,"msg":"(0.000082s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.075+00:00","v":0,"msg":"(0.002347s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.077+00:00","v":0,"msg":"(0.002281s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.079+00:00","v":0,"msg":"(0.002384s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":20,"time":"2023-06-23T00:28:47.079+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.082+00:00","v":0,"msg":"(0.002493s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.085+00:00","v":0,"msg":"(0.002367s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.090+00:00","v":0,"msg":"(0.004897s) select name, setting from pg_settings where name in  ('max_wal_senders', 'max_worker_processes', 'wal_level',  'max_replication_slots', 'max_logical_replication_workers');","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.092+00:00","v":0,"msg":"(0.002392s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.114+00:00","v":0,"msg":"(0.000151s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.114+00:00","v":0,"msg":"(0.000080s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.114+00:00","v":0,"msg":"(0.000100s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":20,"time":"2023-06-23T00:28:47.114+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.114+00:00","v":0,"msg":"(0.000080s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.114+00:00","v":0,"msg":"(0.000089s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.116+00:00","v":0,"msg":"(0.001813s) select name, setting from pg_settings where name in  ('max_wal_senders', 'max_worker_processes', 'wal_level',  'max_replication_slots', 'max_logical_replication_workers');","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.116+00:00","v":0,"msg":"(0.000080s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.116+00:00","v":0,"msg":"Setting up schema","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.145+00:00","v":0,"msg":"(0.002236s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.147+00:00","v":0,"msg":"(0.002459s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.150+00:00","v":0,"msg":"(0.002330s) SET search_path = \"pger\"","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.152+00:00","v":0,"msg":"(0.002530s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":20,"time":"2023-06-23T00:28:47.152+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.155+00:00","v":0,"msg":"(0.002344s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.157+00:00","v":0,"msg":"(0.002369s) SET search_path to pger","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.160+00:00","v":0,"msg":"(0.002306s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.163+00:00","v":0,"msg":"(0.002943s) create schema if not exists pger;\ngrant usage on schema pger to postgres;\ngrant create on schema pger to postgres;\n","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.166+00:00","v":0,"msg":"(0.002944s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.166+00:00","v":0,"msg":"Setting up replication user on source database","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.199+00:00","v":0,"msg":"(0.003637s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.201+00:00","v":0,"msg":"(0.002331s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.203+00:00","v":0,"msg":"(0.002280s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":20,"time":"2023-06-23T00:28:47.204+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.206+00:00","v":0,"msg":"(0.002408s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.208+00:00","v":0,"msg":"(0.002361s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.215+00:00","v":0,"msg":"(0.006228s) drop role if exists pger_su_h1a4fb;\ncreate role pger_su_h1a4fb with password 'postgres' login superuser createdb createrole;\n","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.218+00:00","v":0,"msg":"(0.003014s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.218+00:00","v":0,"msg":"Setting up replication user on target database","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.239+00:00","v":0,"msg":"(0.000148s) SET standard_conforming_strings = ON","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.239+00:00","v":0,"msg":"(0.000100s) SET client_min_messages = 'WARNING'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.240+00:00","v":0,"msg":"(0.000104s) SET DateStyle = 'ISO'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":20,"time":"2023-06-23T00:28:47.240+00:00","v":0,"msg":"Connection established","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.240+00:00","v":0,"msg":"(0.000081s) BEGIN","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.240+00:00","v":0,"msg":"(0.000091s) SET statement_timeout to '5s'","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.250+00:00","v":0,"msg":"(0.009792s) drop role if exists pger_su_h1a4fb;\ncreate role pger_su_h1a4fb with password 'postgres' login superuser createdb createrole;\n","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.279+00:00","v":0,"msg":"(0.028989s) COMMIT","version":"0.1.2"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":3873201,"level":30,"time":"2023-06-23T00:28:47.279+00:00","v":0,"msg":"Setting up groups tables","version":"0.1.2"}
Unable to bootstrap: PG::ConnectionBad: connection to server at "10.7.0.10", port 25432 failed: SSL error: certificate verify failed
connection to server at "10.7.0.10", port 25432 failed: FATAL:  password authentication failed for user "pger_su_h1a4fb"
```

**Comment by gutleib** [comment]
> i see! Does the password have any special chars like a single apostrophe (`'`), exclamation mark (`!`) or a tilde (`~`)?

Actually, I had an `!` in it, but failed to pass it to docker command (before I found that it won't work on x86), gave up and changed to letters and numbers only.

**Comment by shayonj** [comment]
Thank you for the debug logs! Super helpful. And yes, I think I see the issue. We are not parsing the special chars in the password when creating a new user, like `!` or `'`. I will have a fix for it tomorrow/weekend, in `0.1.4` version.

**Comment by gutleib** [comment]
> I see that the password is `postgres` with no special chars, but you mentioned that your password had a special char right?

1) no, the password is not `postgres`

> Did it work after you changed the password? All good, if you are not able to test it like that. Thanks!

2) no, it does not work, though there are only letters and numbers in password

**Comment by shayonj** [comment]
ok got it, thank you for all the debugging messages! I have bunch of fixes planned for 0.1.4, so this will get fixed in it!

**Comment by gutleib** [comment]
upgraded to 0.1.4
erm... the same.
maybe the initial migration able created the very first time messed smth up? What is it's name, I'll try to delete it manually

**Comment by shayonj** [comment]
oh no! yeah that be useful. You can drop the role `pger_su_h1a4fb ` and schema `pger` and try again? Let me know how it goes, thanks

**Comment by shayonj** [comment]
You can also run `pg_easy_replicate cleanup -e --group-name=GROUP_NAME` and try again too, but it may not fully succeed, if the original bootstrap failed mid way too.

**Comment by gutleib** [comment]
Dropped user, did not find such schema.
Started sync, but it doesn't seem to progress. 

I'll generate some more bugreports :)

**Comment by shayonj** [comment]
> Started sync, but it doesn't seem to progress.

Interesting. Please do share any `stats` - https://github.com/shayonj/pg_easy_replicate#stats. Depending on the table / db size, it can take a while

> I'll generate some more bugreports :)

Please do :)

**Comment by shayonj** [comment]
Note: If no tables are added to the publication, the `switchover` will continue to wait for the lag to turn `0`. It is a known thing.

**Comment by gutleib** [comment]
No, back to square one.

Some details: src-db is remote. It has pgbouncer in front of it, and connected to trgt-db via VPN. pg_hba trusts ip of trgt_db, but pg_easy_replicate cannot connect passwordless. pg_bouncer works with password, but I canntot make pg_easy_replicate to connect it. But ` psql $SOURCE_DB_URL` works flawlessly both passwordless and with pw specified in vatiable.

I really am out of ideas

**Comment by shayonj** [comment]
oh interesting! can you clarify a bit more on the `back to square one` ? Is it throwing password auth issues again? Is it reaching till `start_sync`, as mentioned here: https://github.com/shayonj/pg_easy_replicate/issues/16#issuecomment-1605606337

Also any logs will be super helpful

**Comment by shayonj** [comment]
Also, if you don't mind sharing the `pg_easy_replicate` commands you are running. Thanks

**Comment by shayonj** [comment]
You can pg_easy_replicate with `DEBUG=true pg_easy_replicate....`, careful, because it may log the password too.

**Comment by shayonj** [comment]
Also, does your pgbouncer has some allow list of users that can login with it ? If so, `pger_su_h1a4fb` will need to be added to that.

**Comment by shayonj** [comment]
I've released with some enhancements and bug fixes. If you are able to give it a shot, when you have chance and share any feedback that'd be super useful. I have also added a readme section pgbouncer and allowlist here - https://github.com/shayonj/pg_easy_replicate#adding-internal-user-to-pgbouncer-userlist

**Comment by shayonj** [comment]
Closing the issue for now, but please feel free to re-open.

**Comment by gutleib** [comment]
Hi! I'm back to this task, and any help will be appreciated.

> oh interesting! can you clarify a bit more on the back to square one ? Is it throwing password auth issues again? Is it reaching till start_sync, as mentioned here: https://github.com/shayonj/pg_easy_replicate/issues/16#issuecomment-1605606337
> Also any logs will be super helpful

I re-created target db from scratch, and doing everything more or less 'clean slate'. Target DB connectr correcly, on the side of Source DB I had to drop pg_easy_replicate user and schema manually. After that I got following output:
```
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":1976223,"level":30,"time":"2023-07-04T21:31:59.267+00:00","v":0,"msg":"Setting up schema","version":"0.1.7"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":1976223,"level":30,"time":"2023-07-04T21:31:59.323+00:00","v":0,"msg":"Setting up replication user on source database","version":"0.1.7"}
{"name":"pg_easy_replicate","hostname":"db-postgres1z1","pid":1976223,"level":30,"time":"2023-07-04T21:31:59.394+00:00","v":0,"msg":"Setting up replication user on target database","version":"0.1.7"}
Unable to bootstrap: Unable to create user: PG::DependentObjectsStillExist: ERROR:  role "pger_su_h1a4fb" cannot be dropped because some objects depend on it
DETAIL:  privileges for database saas_db
```
db-postgres1z1 is the name of TargetDB.

What logs can be useful?

...and thank you for the tool and help!
